// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVPY7uKt2Mz4oR79ma5-bR9DHvm5NB7YA',
    appId: '1:387167785790:web:29db0af4f31042506d526f',
    messagingSenderId: '387167785790',
    projectId: 'auroratv-f6555',
    authDomain: 'auroratv-f6555.firebaseapp.com',
    storageBucket: 'auroratv-f6555.firebasestorage.app',
    measurementId: 'G-486SREENPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWrSlUhnHb5C5LmA7q_6mvMpEcbvhbddw',
    appId: '1:387167785790:android:380d633b71138ece6d526f',
    messagingSenderId: '387167785790',
    projectId: 'auroratv-f6555',
    storageBucket: 'auroratv-f6555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSMSB_AmwxcRQHBenvq2iuRVKue9ujKE',
    appId: '1:387167785790:ios:993c517cdab5d42e6d526f',
    messagingSenderId: '387167785790',
    projectId: 'auroratv-f6555',
    storageBucket: 'auroratv-f6555.firebasestorage.app',
    iosBundleId: 'com.example.flutterDataTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSMSB_AmwxcRQHBenvq2iuRVKue9ujKE',
    appId: '1:387167785790:ios:993c517cdab5d42e6d526f',
    messagingSenderId: '387167785790',
    projectId: 'auroratv-f6555',
    storageBucket: 'auroratv-f6555.firebasestorage.app',
    iosBundleId: 'com.example.flutterDataTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVPY7uKt2Mz4oR79ma5-bR9DHvm5NB7YA',
    appId: '1:387167785790:web:575337e0b2f4ae076d526f',
    messagingSenderId: '387167785790',
    projectId: 'auroratv-f6555',
    authDomain: 'auroratv-f6555.firebaseapp.com',
    storageBucket: 'auroratv-f6555.firebasestorage.app',
    measurementId: 'G-07XDKCH1VB',
  );
}
